sudo: required
language: java
jdk: openjdk8

services:
  - docker

env:
  global:
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"

script:
  mvn clean install

after_success:
  - docker build -t kernelpanic33/video-recording-server .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push kernelpanic33/video-recording-server:latest
